features:
  custom_errors:
    enabled: true
  slack_notifications:
    enabled: true

mailer:
  delivery_method: 'smtp'
  smtp_settings:
    port: 587
    user_name: <%= ENV['SENDGRID_USERNAME'] %>
    password: <%= ENV['SENDGRID_PASSWORD'] %>
    address: 'smtp.sendgrid.net'
    domain: 'heroku.com'
    authentication: 'plain'

disqus:
  shortname: 'agileventures'
