features:
  custom_errors:
    enabled: true
  slack:
    notifications:
      enabled: true
    invites:
      enabled: true

mailer:
  delivery_method: 'smtp'
  smtp_settings:
    port: 587
    user_name: <%= ENV['SENDGRID_USERNAME'] %>
    password: <%= ENV['SENDGRID_PASSWORD'] %>
    address: 'smtp.sendgrid.net'
    domain: 'heroku.com'
    authentication: 'plain'
  url_host: 'agileventures.org'

disqus:
  shortname: 'agileventures'
  api_key:  <%= ENV['DISQUS_API_KEY']  %>
  secret_key:  <%= ENV['DISQUS_SECRET_KEY']  %>
