features:
  edit_static_pages:
    enabled: true
  get_next_scrum:
    enabled: true
  get_next_scrum_homepage:
    enabled: true
  slack:
    notifications:
      enabled: false
    invites:
      enabled: false
  twitter:
    notifications:
      enabled: true

  email_registrations:
    enabled: true

api:
  premium_subscriptions_token: 'TEST'

mailer:
  delivery_method: 'test'

privileged_users: 'admin@privileged.com, chesa@example.com, random@random.com'

agile_bot_url: https://agile-bot.herokuapp.com
